package at.tugraz.genome.vos;

import java.util.Hashtable;
import java.util.LinkedHashMap;

public class BrainSpecies
{
  public final static Hashtable<String,String> adductIonisations = new Hashtable<String,String>(){

    private static final long serialVersionUID = 4812449157127182890L;

    {
      put("H","+H+");
      put("Na","+Na+");
      put("-OH","+H+ -H2O");
      put("HCOO","+HCOO-");
      put("-H","-H+");
      put("Cl","+Cl-");
    }
  };
  
  public final static Hashtable<String,String> modToIonisationMode = new Hashtable<String,String>(){

    private static final long serialVersionUID = -8377830062761031695L;

    {
      put("H","+");
      put("Na","+");
      put("-OH","+");
      put("HCOO","-");
      put("-H","-");
      put("Cl","-");
    }
  };
  
  public static LinkedHashMap<String,LinkedHashMap<String,ReferenceInfoVO>> getSphBaseSpeciesOrbitrap(){
    LinkedHashMap<String,LinkedHashMap<String,ReferenceInfoVO>> species = new LinkedHashMap<String,LinkedHashMap<String,ReferenceInfoVO>>();
    LinkedHashMap<String,ReferenceInfoVO> molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1", new ReferenceInfoVO("d18:1",new double[]{3.00d},true,false));
    species.put("d18:1", molSpecies);
    return species;
  }
  
  public static LinkedHashMap<String,LinkedHashMap<String,ReferenceInfoVO>> getCerSpeciesOrbitrap(){
    LinkedHashMap<String,LinkedHashMap<String,ReferenceInfoVO>> species = new LinkedHashMap<String,LinkedHashMap<String,ReferenceInfoVO>>();
    LinkedHashMap<String,ReferenceInfoVO> molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n14:0", new ReferenceInfoVO("d18:1/n14:0",new double[]{19.80d},true,false));
    species.put("d32:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n16:0", new ReferenceInfoVO("d18:1/n16:0",new double[]{22.14d},true,false));
    species.put("d34:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:2/n16:0", new ReferenceInfoVO("d18:2/n16:0",new double[]{20.37d},true,false));
    species.put("d34:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n17:0", new ReferenceInfoVO("d18:1/n17:0",new double[]{23.32d},true,false));
    molSpecies.put("d17:1/n18:0", new ReferenceInfoVO("d18:1/n17:0",new double[]{23.32d},true,false));
    species.put("d35:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:0/n18:0", new ReferenceInfoVO("d18:0/n18:0",new double[]{25.00d},true,false));
    species.put("d36:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n18:0", new ReferenceInfoVO("d18:1/n18:0",new double[]{24.39d},true,false));
    molSpecies.put("d16:0/n20:1", new ReferenceInfoVO("d16:0/n20:1",new double[]{24.39d},true,false));
    species.put("d36:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/h18:0", new ReferenceInfoVO("d18:1/h18:0",new double[]{21.60d},true,false));
    species.put("t36:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:2/n18:0", new ReferenceInfoVO("d18:2/n18:0",new double[]{22.80d},true,false));
    species.put("d36:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n19:0", new ReferenceInfoVO("d18:1/n19:0",new double[]{25.41d},true,false));
    molSpecies.put("d19:1/n18:0", new ReferenceInfoVO("d19:1/n18:0",new double[]{25.41d},true,false));
    molSpecies.put("d17:0/n20:1", new ReferenceInfoVO("d17:0/n20:1",new double[]{25.41d},true,false));
    species.put("d37:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("t18:0/n20:0", new ReferenceInfoVO("t18:0/n20:0",new double[]{25.28d},true,false));
    species.put("t38:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n20:0", new ReferenceInfoVO("d18:1/n20:0",new double[]{26.35d},true,false));
    molSpecies.put("d20:1/n18:0", new ReferenceInfoVO("d20:1/n18:0",new double[]{26.35d},true,false));
    species.put("d38:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/h20:0", new ReferenceInfoVO("d18:1/h20:0",new double[]{23.85d},true,false));
    species.put("t38:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:2/n20:0", new ReferenceInfoVO("d18:2/n20:0",new double[]{24.95d},true,false));
    molSpecies.put("d20:2/n18:0", new ReferenceInfoVO("d20:2/n18:0",new double[]{24.95d},true,false));
    molSpecies.put("d18:1/n20:1", new ReferenceInfoVO("d18:1/n20:1",new double[]{24.95d},true,false));
    species.put("d38:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n21:0", new ReferenceInfoVO("d18:1/n21:0",new double[]{27.30d},true,false));
    species.put("d39:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:0/n22:0", new ReferenceInfoVO("d18:0/n22:0",new double[]{28.62d},true,false));
    species.put("d40:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("t18:0/n22:0", new ReferenceInfoVO("t18:0/n22:0",new double[]{27.19,27.55d},true,false));
    species.put("t40:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n22:0", new ReferenceInfoVO("d18:1/n22:0",new double[]{28.14d},true,false));
    species.put("d40:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("t40:1", new ReferenceInfoVO("t40:1",new double[]{27.30d},true,false));
    species.put("t40:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n22:1", new ReferenceInfoVO("d18:1/n22:1",new double[]{26.58d},true,false));
    molSpecies.put("d18:2/n22:0", new ReferenceInfoVO("d18:2/n22:0",new double[]{26.58d},true,false));
    species.put("d40:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("m41:0", new ReferenceInfoVO("m41:0",new double[]{30.41d},false,false));
    species.put("m41:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d41:0", new ReferenceInfoVO("d41:0",new double[]{29.46d},true,false));
    species.put("d41:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("t18:0/n23:0", new ReferenceInfoVO("t18:0/n23:0",new double[]{28.07d,28.46d},true,false));
    species.put("t41:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n23:0", new ReferenceInfoVO("d18:1/n23:0",new double[]{29.03d},true,false));
    species.put("d41:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/h23:0", new ReferenceInfoVO("d18:1/h23:0",new double[]{26.82d},true,false));
    species.put("t41:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n23:1", new ReferenceInfoVO("d18:1/n23:1",new double[]{27.46d},true,false));
    molSpecies.put("d18:2/n23:0", new ReferenceInfoVO("d18:2/n23:0",new double[]{27.46d},true,false));
    species.put("d41:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("m42:0", new ReferenceInfoVO("m42:0",new double[]{31.03d},false,false));
    species.put("m42:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:0/n24:0", new ReferenceInfoVO("d18:0/n24:0",new double[]{30.19d},true,false));
    species.put("d42:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("t18:0/n24:0", new ReferenceInfoVO("t18:0/n24:0",new double[]{28.89d},true,false));
    species.put("t42:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:0/n24:1", new ReferenceInfoVO("d18:0/n24:1",new double[]{28.67d},true,false));
    molSpecies.put("d18:1/n24:0", new ReferenceInfoVO("d18:1/n24:0",new double[]{29.78d},true,false));
    species.put("d42:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("t18:0/n24:1", new ReferenceInfoVO("t18:0/n24:1",new double[]{27.26d},true,false));
    molSpecies.put("d18:1/h24:0", new ReferenceInfoVO("d18:1/h24:0",new double[]{27.78d},true,false));
    molSpecies.put("t42:1", new ReferenceInfoVO("t42:1",new double[]{28.98d},true,false));
    species.put("t42:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n24:1", new ReferenceInfoVO("d18:1/n24:1",new double[]{28.28d},true,false));
    molSpecies.put("d18:2/n24:0", new ReferenceInfoVO("d18:2/n24:0",new double[]{28.82d},true,false));
    molSpecies.put("d18:0/n24:2", new ReferenceInfoVO("d18:0/n24:2",new double[]{26.55d},true,false));
    species.put("d42:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/h24:1", new ReferenceInfoVO("d18:1/h24:1",new double[]{26.00d},true,false));
    molSpecies.put("t42:2", new ReferenceInfoVO("t42:2",new double[]{27.39d},true,false));
    species.put("t42:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n24:2", new ReferenceInfoVO("d18:1/n24:2",new double[]{26.96d},true,false));
    molSpecies.put("d18:2/n24:1", new ReferenceInfoVO("d18:2/n24:1",new double[]{26.96d},true,false));
    species.put("d42:3", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("m43:0", new ReferenceInfoVO("m43:0",new double[]{31.67d},false,false));
    species.put("m43:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d43:0", new ReferenceInfoVO("d43:0",new double[]{30.94d},false,false));
    species.put("d43:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n25:0", new ReferenceInfoVO("d18:1/n25:0",new double[]{30.55d},true,false));
    species.put("d43:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n25:1", new ReferenceInfoVO("d18:1/n25:1",new double[]{29.05d},true,false));
    species.put("d43:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("m44:0", new ReferenceInfoVO("m44:0",new double[]{32.31d},false,false));
    species.put("m44:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("m44:1", new ReferenceInfoVO("m44:1",new double[]{31.07d},false,false));
    species.put("m44:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n26:0", new ReferenceInfoVO("d18:1/n26:0",new double[]{31.17d},true,false));
    species.put("d44:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d20:1/n24:1", new ReferenceInfoVO("d20:1/n24:1",new double[]{29.71d},true,false));
    molSpecies.put("d18:1/n26:1", new ReferenceInfoVO("d18:1/n26:1",new double[]{29.71d},true,false));
    species.put("d44:2", molSpecies);
    return species;
  }
  
  public static LinkedHashMap<String,LinkedHashMap<String,ReferenceInfoVO>> getCer1PSpeciesOrbitrap(){
    LinkedHashMap<String,LinkedHashMap<String,ReferenceInfoVO>> species = new LinkedHashMap<String,LinkedHashMap<String,ReferenceInfoVO>>();
    return species;
  }
  

  public static LinkedHashMap<String,LinkedHashMap<String,ReferenceInfoVO>> getHexCerSpeciesOrbitrap(){
    LinkedHashMap<String,LinkedHashMap<String,ReferenceInfoVO>> species = new LinkedHashMap<String,LinkedHashMap<String,ReferenceInfoVO>>();
    LinkedHashMap<String,ReferenceInfoVO> molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n16:0", new ReferenceInfoVO("d18:1/n16:0",new double[]{20.03d},true,false));
    species.put("d34:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n18:0", new ReferenceInfoVO("d18:1/n18:0",new double[]{22.42d},true,false));
    species.put("d36:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/h18:0", new ReferenceInfoVO("d18:1/h18:0",new double[]{21.62d},true,false));
    species.put("t36:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d36:2", new ReferenceInfoVO("d36:2",new double[]{20.67d},true,false));
    species.put("d36:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("t36:2", new ReferenceInfoVO("t36:2",new double[]{19.85d},true,false));
    species.put("t36:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d38:1", new ReferenceInfoVO("d38:1",new double[]{24.62d},true,false));
    species.put("d38:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/h20:0", new ReferenceInfoVO("d18:1/h20:0",new double[]{23.92d},true,false));
    species.put("t38:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n21:0", new ReferenceInfoVO("d18:1/n21:0",new double[]{25.60d},true,false));
    species.put("d39:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("t39:1", new ReferenceInfoVO("t39:1",new double[]{25.01d},true,false));
    species.put("t39:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d40:0", new ReferenceInfoVO("d40:0",new double[]{27.10d},true,false));
    species.put("d40:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("t40:0", new ReferenceInfoVO("t40:0",new double[]{26.50d},true,false));
    species.put("t40:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n22:0", new ReferenceInfoVO("d18:1/n22:0",new double[]{26.58d},true,false));
    molSpecies.put("d20:0/n20:1", new ReferenceInfoVO("d20:0/n20:1",new double[]{26.58d},true,false));    
    species.put("d40:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("t40:1", new ReferenceInfoVO("t40:1",new double[]{26.01d},true,false));
    species.put("t40:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n22:1", new ReferenceInfoVO("d18:1/n22:1",new double[]{24.78d,25.17},true,false));
    molSpecies.put("d18:2/n22:0", new ReferenceInfoVO("d18:2/n22:0",new double[]{24.78d,25.17},true,false));
    species.put("d40:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:2/h22:0", new ReferenceInfoVO("d18:2/h22:0",new double[]{24.10, 24.58d},true,false));
    species.put("t40:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:0/n23:0", new ReferenceInfoVO("d18:0/n23:0",new double[]{28.01d},true,false));
    species.put("d41:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d20:0/h21:0", new ReferenceInfoVO("d20:0/h21:0",new double[]{27.42d},true,false));
    species.put("t41:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n23:0", new ReferenceInfoVO("d18:1/n23:0",new double[]{27.48d},true,false));
    species.put("d41:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/h23:0", new ReferenceInfoVO("d18:1/h23:0",new double[]{26.96d},true,false));
    species.put("t41:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:2/n23:0", new ReferenceInfoVO("d18:2/n23:0",new double[]{25.73d},true,false));
    molSpecies.put("d18:1/n23:1", new ReferenceInfoVO("d18:1/n23:1",new double[]{26.21d},true,false));    
    species.put("d41:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/h23:1", new ReferenceInfoVO("d18:1/h23:1",new double[]{25.12d},true,false)); 
    molSpecies.put("d18:2/h23:0", new ReferenceInfoVO("d18:2/h23:0",new double[]{25.58d},true,false));
    species.put("t41:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:0/n24:0", new ReferenceInfoVO("d18:0/n24:0",new double[]{28.82d},true,false));
    species.put("d42:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("t42:0", new ReferenceInfoVO("t42:0",new double[]{28.32},true,false));
    species.put("t42:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n24:0", new ReferenceInfoVO("d18:1/n24:0",new double[]{28.33d,27.17d},true,false));
    species.put("d42:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/h24:0", new ReferenceInfoVO("d18:1/h24:0",new double[]{27.83d},true,false));
    species.put("t42:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n24:1", new ReferenceInfoVO("d18:1/n24:1",new double[]{26.62d,27.12d},true,false));
    molSpecies.put("d18:2/n24:0", new ReferenceInfoVO("d18:2/n24:0",new double[]{26.62d,27.12d},true,false));
    species.put("d42:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/h24:1", new ReferenceInfoVO("d18:1/h24:1",new double[]{26.07d},true,false));
    species.put("t42:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n24:2", new ReferenceInfoVO("d18:1/n24:2",new double[]{25.23d},true,false));
    species.put("d42:3", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/h24:2", new ReferenceInfoVO("d18:1/h24:2",new double[]{24.66d},true,false));
    molSpecies.put("d18:0/h24:3", new ReferenceInfoVO("d18:0/h24:3",new double[]{24.66d},true,false));    
    species.put("t42:3", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n25:0", new ReferenceInfoVO("d18:1/n25:0",new double[]{29.16d},true,false));
    species.put("d43:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/h25:0", new ReferenceInfoVO("d18:1/h25:0",new double[]{28.67d},true,false));
    species.put("t43:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n25:1", new ReferenceInfoVO("d18:1/n25:1",new double[]{27.58d},true,false));
    molSpecies.put("d18:2/n25:0", new ReferenceInfoVO("d18:2/n25:0",new double[]{27.58d},true,false));
    species.put("d43:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/h25:1", new ReferenceInfoVO("d18:1/h25:1",new double[]{26.96d},true,false));
    species.put("t43:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d43:3", new ReferenceInfoVO("d43:3",new double[]{26.21d},true,false));
    species.put("d43:3", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d44:1", new ReferenceInfoVO("d44:1",new double[]{29.92d},true,false));
    species.put("d44:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("t44:1", new ReferenceInfoVO("t44:1",new double[]{29.33d},true,false));
    species.put("t44:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n26:1", new ReferenceInfoVO("d18:1/n26:1",new double[]{28.26d},true,false));
    species.put("d44:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/h26:1", new ReferenceInfoVO("d18:1/h26:1",new double[]{27.69d},true,false));
    species.put("t44:2", molSpecies);
    return species;
  }

  
  public static LinkedHashMap<String,LinkedHashMap<String,ReferenceInfoVO>> getSMSpeciesOrbitrap(){
    LinkedHashMap<String,LinkedHashMap<String,ReferenceInfoVO>> species = new LinkedHashMap<String,LinkedHashMap<String,ReferenceInfoVO>>();
    LinkedHashMap<String,ReferenceInfoVO> molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:0/n12:0", new ReferenceInfoVO("d18:0/n12:0",new double[]{12.26d,12.73d},true,false));
    species.put("d30:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n14:0", new ReferenceInfoVO("d18:1/n14:0",new double[]{16.28d},true,false));
    species.put("d32:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d33:1", new ReferenceInfoVO("d33:1",new double[]{17.60d},true,false));
    species.put("d33:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d34:0", new ReferenceInfoVO("d34:0",new double[]{19.69d},true,false));
    species.put("d34:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("t18:0/n16:0", new ReferenceInfoVO("t18:0/n16:0",new double[]{17.73d},true,false));
    species.put("t34:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n16:0", new ReferenceInfoVO("d18:1/n16:0",new double[]{18.85d},true,false));
    molSpecies.put("d16:1/n18:0", new ReferenceInfoVO("d16:1/n18:0",new double[]{18.85d},true,false));
    species.put("d34:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("t34:1", new ReferenceInfoVO("t34:1",new double[]{18.01d},true,false));
    species.put("t34:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d34:2", new ReferenceInfoVO("d34:2",new double[]{16.94d},true,false));
    species.put("d34:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n17:0", new ReferenceInfoVO("d18:1/n17:0",new double[]{20.12d},true,false));
    species.put("d35:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d36:0", new ReferenceInfoVO("d36:0",new double[]{22.08d},true,false));
    species.put("d36:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n18:0", new ReferenceInfoVO("d18:1/n18:0",new double[]{21.35d},true,false));
    species.put("d36:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:2/n18:0", new ReferenceInfoVO("d18:2/n18:0",new double[]{19.58d},true,false));
    species.put("d36:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n20:0", new ReferenceInfoVO("d18:1/n20:0",new double[]{23.60d},true,false));
    molSpecies.put("d20:1/n18:0", new ReferenceInfoVO("d20:1/n18:0",new double[]{23.60d},true,false));
    species.put("d38:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d40:0", new ReferenceInfoVO("d40:0",new double[]{26.37d},true,false));
    species.put("d40:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("t40:0", new ReferenceInfoVO("t40:0",new double[]{24.90d},true,false));
    species.put("t40:0", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n22:0", new ReferenceInfoVO("d18:1/n22:0",new double[]{25.78d},true,false));
    species.put("d40:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n22:1", new ReferenceInfoVO("d18:1/n22:1",new double[]{23.83d},true,false));
    species.put("d40:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n23:0", new ReferenceInfoVO("d18:1/n23:0",new double[]{26.78d},true,false));
    species.put("d41:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:0/n24:1", new ReferenceInfoVO("d18:0/n24:1",new double[]{26.39d},true,false));
    molSpecies.put("d18:1/n24:0", new ReferenceInfoVO("d18:1/n24:0",new double[]{27.69d},true,false));
    species.put("d42:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("t42:1", new ReferenceInfoVO("t42:1",new double[]{24.95d},true,false));
    species.put("t42:1", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d18:1/n24:1", new ReferenceInfoVO("d18:1/n24:1",new double[]{25.80d},true,false));
    species.put("d42:2", molSpecies);
    molSpecies = new LinkedHashMap<String,ReferenceInfoVO>();
    molSpecies.put("d43:2", new ReferenceInfoVO("d43:2",new double[]{26.71d},true,false));
    species.put("d43:2", molSpecies);
    return species;
  }
}
