/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_tugraz_genome_lda_quantification_SavGolJNI */

#ifndef _Included_at_tugraz_genome_lda_quantification_SavGolJNI
#define _Included_at_tugraz_genome_lda_quantification_SavGolJNI
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     at_tugraz_genome_lda_quantification_SavGolJNI
	* Method:    cudaCapableDeviceNative
	* Signature: ()Z
	*/
	JNIEXPORT jboolean JNICALL Java_at_tugraz_genome_lda_quantification_SavGolJNI_cudaCapableDeviceNative
	(JNIEnv *, jobject);

	/*
	* Class:     at_tugraz_genome_lda_quantification_SavGolJNI
	* Method:    initMallocNative
	* Signature: (I)J
	*/
	JNIEXPORT jlong JNICALL Java_at_tugraz_genome_lda_quantification_SavGolJNI_initMallocNative
	(JNIEnv *, jobject, jint);

	/*
	* Class:     at_tugraz_genome_lda_quantification_SavGolJNI
	* Method:    SmoothNative
	* Signature: ([[FIFIIIJ)[F
	*/
	JNIEXPORT jfloatArray JNICALL Java_at_tugraz_genome_lda_quantification_SavGolJNI_SmoothNative
	(JNIEnv *, jobject, jobjectArray, jint, jfloat, jint, jint, jint, jlong);

	/*
	* Class:     at_tugraz_genome_lda_quantification_SavGolJNI
	* Method:    FreesNative
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_at_tugraz_genome_lda_quantification_SavGolJNI_FreesNative
	(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
